version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - "./data-example/mqtt/conf:/mosquitto/config"
      - "./data/mqtt/data:/mosquitto/data"

  nodered:
    image: nodered/node-red
    environment:
      - TZ=Europe/Rome
    ports:
      - "1880:1880"
    restart: unless-stopped
    volumes:
      - "./data/nodered/data/:/data"

  hass:
    image: ghcr.io/home-assistant/home-assistant
    environment:
      - TZ=Europe/Rome
    restart: unless-stopped
    # if on Linux (as in a real life scenario), comment ports section and use
    # network_mode: host
    ports:
      - "8123:8123"
    volumes:
      - "./data/hass/config:/config"

#  esphome:
#    image: esphome/esphome
#    volumes:
#      - "./data/esphome/config:/config"
#      - "/etc/localtime:/etc/localtime:ro"
#    restart: unless-stopped
#    privileged: true
#    network_mode: host
